# Render automatically injects a specific port variable; if missing, fall back to 8081 locally
server.port=${PORT:8081}

# PostgreSQL Spring Connection Framework
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hospi_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:flash}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration Layer
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true